# Generated by Django 3.2.4 on 2021-10-15 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('Endereco', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('ACRE', 'AC'), ('ALAGOAS', 'AL'), ('AMAPÁ', 'AP'), ('AMAZONAS', ''), ('BAHIA', 'BA'), ('CEÁRA', 'CE'), ('DISTRITO FEDERAL', 'DF'), ('ESPÍRITO SANTO', 'ES'), ('GOÍAS', 'GO'), ('MARANHÃO', 'MA'), ('MATO GROSSO ', 'MT'), ('MATO GROSSO DO SUL', 'MINAS'), ('MINAS GERAIS', 'MG'), ('PARA', 'PA'), ('PARANÁ', 'PR'), ('PARAÍBA', 'PB'), ('PERNAMBUCO', 'PE'), ('PIAUÍ', 'PI'), ('RIO DE JANEIRO', 'RJ'), ('RIO GRANDE DO NORTE', 'RN'), ('RIO GRANDE DO SUL', 'RS'), ('RONDÔNIA', 'RO'), ('RORAIMA', 'RR'), ('SANTA CATARINA', 'SC'), ('SERGIPE', 'SE'), ('TOCANTINS', 'TO')], max_length=22)),
                ('bairro', models.CharField(max_length=30)),
                ('creci', models.CharField(max_length=6)),
                ('estado_creci', models.CharField(choices=[('ACRE', 'AC'), ('ALAGOAS', 'AL'), ('AMAPÁ', 'AP'), ('AMAZONAS', ''), ('BAHIA', 'BA'), ('CEÁRA', 'CE'), ('DISTRITO FEDERAL', 'DF'), ('ESPÍRITO SANTO', 'ES'), ('GOÍAS', 'GO'), ('MARANHÃO', 'MA'), ('MATO GROSSO ', 'MT'), ('MATO GROSSO DO SUL', 'MINAS'), ('MINAS GERAIS', 'MG'), ('PARA', 'PA'), ('PARANÁ', 'PR'), ('PARAÍBA', 'PB'), ('PERNAMBUCO', 'PE'), ('PIAUÍ', 'PI'), ('RIO DE JANEIRO', 'RJ'), ('RIO GRANDE DO NORTE', 'RN'), ('RIO GRANDE DO SUL', 'RS'), ('RONDÔNIA', 'RO'), ('RORAIMA', 'RR'), ('SANTA CATARINA', 'SC'), ('SERGIPE', 'SE'), ('TOCANTINS', 'TO')], max_length=22)),
                ('imagem_perfil', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem_capa', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem_formulario', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negociacao', models.CharField(choices=[('VENDA', 'VENDA'), ('ALUGA', 'ALUGA'), ('COMPRA', 'COMPRA')], max_length=6)),
                ('status', models.CharField(choices=[('LANÇAMENTO', 'LANÇAMENTO'), ('EM OBRAS', 'EM OBRAS'), ('PRONTO PARA MORAR', 'PRONTO PARA MORAR')], max_length=18)),
                ('tipo_imovel', models.CharField(choices=[('APARTAMENTO', 'APARTAMENTO'), ('CASA', 'CASA'), ('TERRENO', 'TERRENO'), ('COMERCIAL', 'COMERCIAL'), ('GALPÃO', 'GALPÃO'), ('CHACARÁ', 'CHACARÁ'), ('SÍTIO', 'SÍTIO'), ('FAZENDA', 'FAZENDA')], max_length=12)),
                ('titulo_anuncio', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=150)),
                ('imagem1', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem2', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem3', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem4', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem5', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem6', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem7', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem8', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem9', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem10', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=100, size=[660, 540], upload_to='media/')),
                ('anunciado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
