# Generated by Django 3.2.8 on 2021-10-19 16:18

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_anuncio_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_perfil', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem_capa', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
                ('imagem_formulario', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=100, size=[660, 540], upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='imagem_capa',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='imagem_formulario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='imagem_perfil',
        ),
    ]
